### ISSUE TITLE
Code stuck at the while loop with 'asdf' getIntegerSignal

### ISSUE THREAD

**Issue by Jarrome** [ctmakro/vrepper#5]
Hi, @ctmakro . I just found your vrepper and it is really convenient to use.

But when I run your demo with test_body_joint.py and test_cartpole.py. 
Both of them are stuck. It may because the simulation does not stop as it should do.

Could you help me to figure it out?

---
What I change here.
I'm not sure if the gym is different that before, reset and step just cannot call.
So I change the function name _reset => reset and _step => step to make it able to run.
Could you please also tell your version of gym?

**Comment by ctmakro** [comment]
it's been a long time since i last use Gym. i'm currently in the middle of something and don't have the time for solving your specific problem. i suggest you try https://github.com/fgolemo/vrepper and see if his improvement solves your problem.

**Comment by Jarrome** [comment]
Problem solved.

`stop_blocking_simulation` has been deprecated, but the test file still have it. 

As it suggests I change to `stop_simulation` and it runs well!
Wow, your vrepper is really nice!
